various updates

diff --git a/qdp b/qdp
--- a/qdp
+++ b/qdp
@@ -1,10 +1,12 @@
-#!/bin/sh
+#!/bin/bash
 # quick & dirty plot
-# uses pyxplot to create a quick & dirty xy plot from a single-file with a single-column
+# uses pyxplot to create a quick & dirty xy plot from a single-file
 
 # defcolors=(blue olivegreen brickred grey sepia tan black magenta periwinkle orange)
 xcol=1
-ycol=(2)
+ycol=()
+key="above"
+width=12
 
 # defaults
 defaultcolor=(blue black green brickred gray turquoise magenta pinegreen sepia burntorange)   
@@ -17,31 +19,37 @@ usage: $0 [options] [-o output] [datafile]
  if no output is given, basename is assumed equal to datafile
  if neither output nor datafile given, basename output is qdp
  both .png and .pdf will be appended to output
+     --ycol "<ints>"         set y columns in datafile, default all
      --xcol <int>            set x column in datafile, default 1
-     --ycol <int>            set y columns in datafile, default 2
      --xlabel <string>       set x axis label, default none
      --ylabel <string>       set y axis label, default none
      --xrange <range>        set x axis range, default auto
      --yrange <range>        set y axis range, default auto
-     --with <string>         set with, default linespoints
-     --lt <string>           set linetype, default 1
-     --lw <float>            set linewdith, default 1
-     --plw <float>           set pointlinewdiths
-     --ps <float>            set pointsizes
-     --pt <int>              set pointtype
-     --pi <int>              set pointinterval (extension to pyxplot)
-     --color <string>        set colors
-     --ti <string>           set data title, default none
+     --grid                  set grid, default no
+     --width <float>         set plot width in cm, default 12
+     --with "<strings>"      set plotting styles, default linespoints
+     --lt "<strings>"        set linetypes, default 1
+     --lw "<floats>"         set linewdiths, default 1
+     --plw "<floats>"        set pointlinewidths, default 1
+     --ps "<float>"          set pointsizes, default 1
+     --pt "<ints>"           set pointtype, default some values
+     --pi "<ints>"           set pointinterval (extension to pyxplot)
+     --color "<strings>"     set colors, default some values
+     --ti "<strings>"        set column titles, default none
      --plottitle <string>    set plot title, default none
-     --key <string>          set key location, default top right
+     --key <string>          set key location, default above
      --pre <string>          execute pyxplot commands in  <string> before plotting
      --header <file>         use <file> as template instead of default
+     --debug                 leave the .ppl file for inspection and edition
+
+ quotes are needed if several columns are to be plotted
+ see the examples subdirectory
 EOF
   exit 1
 }
 
 
-ARGS=`getopt -o ":o:h" -l "plottitle:,ti:,xcol:,ycol:,xlabel:,ylabel:,xrange:,yrange:,with:,lt:,lw:,plw:,ps:,pt:,pi:,color:,pre:,header:,key:,help" -n "$0" -- "$@"`
+ARGS=`getopt -o ":o:h" -l "plottitle:,ti:,xcol:,ycol:,xlabel:,ylabel:,xrange:,yrange:,grid,width:,with:,lt:,lw:,plw:,ps:,pt:,pi:,color:,pre:,header:,key:,debug,,help" -n "$0" -- "$@"`
 # echo $ARGS
 if [ $? -ne 0 ];
 then
@@ -120,12 +128,23 @@ do
       fi
       shift 2;;
 
+    --width)
+      if [ -n "$2" ];
+      then
+        width=$2
+      fi
+      shift 2;;
+
     --with)
       if [ -n "$2" ];
       then
         with=($2)
       fi
       shift 2;;
+
+    --grid)
+      grid=1
+      shift 1;;
 
     --lt)
       if [ -n "$2" ];
@@ -197,6 +216,10 @@ do
       fi
       shift 2;;
 
+    --debug)
+      debug=1
+      shift 1;;
+
     --)
       shift
       break;;
@@ -212,6 +235,10 @@ else
   data="$1"
 fi
 
+if [ ! -f "$data" ]; then
+ echo "error: cannot open ${data}"
+ exit 1;
+fi
 
 if [ -z "$output" ]; then
   if [ -z "$1" ]; then
@@ -221,8 +248,20 @@ if [ -z "$output" ]; then
   fi
 fi
 
-# pplfile="qdp.ppl"
-pplfile=`mktemp`
+if [ ! -z "$debug" ]; then
+  pplfile="${output}.ppl"
+  if [ -e ${pplfile} ]; then
+    echo "error: the debug option was given and ${pplfile} already exists"
+    exit 1
+  fi
+else
+  pplfile=`mktemp`
+fi
+
+cat << EOF > ${pplfile}
+# automatically generated by qdp on `date`
+#
+EOF
 
 if [ ! -z "${header}" ]; then
   if [ ! -e "${header}" ]; then
@@ -232,13 +271,15 @@ if [ ! -z "${header}" ]; then
   cat ${header} >> ${pplfile}
 else
   # default header
-  echo "set preamble \"\\usepackage{amsmath}\"" >> ${pplfile}
-  echo "set width 12*unit(cm)" >> ${pplfile}
-  echo "set axis x arrow nomirrored" >> ${pplfile}
-  echo "set axis y arrow nomirrored" >> ${pplfile}
-  echo "set nomxtics"  >> ${pplfile}
-  echo >> ${pplfile}
-  echo "set style data linespoints" >> ${pplfile}
+  cat << EOF >> ${pplfile}
+set preamble "\\usepackage{amsmath}"
+set width ${width}*unit(cm)
+set axis x arrow nomirrored
+set axis y arrow nomirrored
+#set nomxtics
+
+set style data linespoints
+EOF
 fi
 
 if [ ! -z "${pre}" ]; then
@@ -265,14 +306,51 @@ fi
 if [ ! -z "$key" ]; then
  echo "set key $key" >> ${pplfile}
 fi
+if [ ! -z "$grid" ]; then
+ echo "set grid" >> ${pplfile}
+fi
 
+# we translate points to dashes because pdflatex does not like points in filenames
 echo "set terminal pdf" >> ${pplfile}
 escappedoutput=`echo $output | sed s/\\\\./-/g`
 echo "set output \"$escappedoutput.pdf\"" >> ${pplfile}
 
+ncols=${#ycol[@]}
 
-# ncols=`cat file | awk '{print NF}'`
-echo -n "plot " >> ${pplfile}
+# if no ycol argument is given, sweep all the columns
+if [ $ncols -eq 0 ]; then
+ ncols=`grep -v \# $data | head -n1 | awk '{print NF}'`
+ last=`expr ${ncols} - 2`
+ for i in `seq 0 ${last}`; do
+  ycol[$i]=`expr $i + 2`
+ done
+fi
+
+# if not explicitly given, choose a suitable point interval
+if [[ -z "${with[0]}" ]] && [[ -z "${pi[0]}" ]] ; then
+#  x0=`grep -v \# $data | head -n1 | awk -v col=$xcol '{print $col}'`
+#  xn=`grep -v \# $data | tail -n1 | awk -v col=$xcol '{print $col}'`
+ n=`grep -v \# $data | wc -l`
+ if [ $n -gt 10 ]; then
+  last=`expr ${ncols} - 2`
+  for i in `seq 0 ${last}`; do
+   pi[$i]=`echo "scale=3; (0.5+${RANDOM}.0/32726.0)*($n/10.0)" | bc`
+  done
+ fi
+fi
+
+# if no titles given, check if the file contains a header with the column title
+if [[ -z "${ti[0]}" ]] && [[ "`head -n1 $data | cut -c1`" == "#" ]]; then
+ last=`expr ${ncols} - 2`
+ for i in `seq 0 ${last}`; do
+  ti[$i]=`head -n1 $data | cut -c1 --complement | awk -v col=${ycol[$i]} '{print $col}' | sed s/_/\\\\\\\\_/`
+ done
+ if [ -z "$xlabel" ]; then
+  echo "set xlabel \"`head -n1 $data | cut -c1 --complement | awk -v col=${xcol} '{print $col}' | sed s/_/\\\\\\\\_/`\"" >> ${pplfile}
+ fi
+fi
+
+echo "plot \\" >> ${pplfile}
 
 i=0
 while [ ! -z "${ycol[$i]}" ]; do
@@ -305,10 +383,10 @@ while [ ! -z "${ycol[$i]}" ]; do
     echo -n " color ${defaultcolor[$i]}"  >> ${pplfile}
   fi
 
-  if [ ! -z "${ti[$i]}" ];    then
-   echo -n " ti \"${ti[$i]}\""    >> ${pplfile}
+  if [ ! -z "${ti[$i]}" ];           then
+   echo -n " ti \"${ti[$i]}\""             >> ${pplfile}
   else
-   echo -n " ti \"\""             >> ${pplfile}
+   echo -n " ti \"\""                      >> ${pplfile}
   fi
 
  else
@@ -349,7 +427,7 @@ while [ ! -z "${ycol[$i]}" ]; do
 
  i=`echo $i + 1 | bc`
  if [ ! -z "${ycol[$i]}" ]; then
-  echo -n ", " >> ${pplfile}
+  echo ",\\" >> ${pplfile}
  fi
 done
 
@@ -358,10 +436,13 @@ echo >> ${pplfile}
 
 echo "set terminal png dpi 127" >> ${pplfile}
 echo "set output \"$escappedoutput.png\"" >> ${pplfile}
-
 echo "replot" >> ${pplfile}
 
-# TODO: debugo
-# cat ${pplfile}
+
 pyxplot ${pplfile}
-# rm ${pplfile}
+
+if [ ! -z "$debug" ]; then
+ echo "debug: plot file saved as ${pplfile}"
+else
+ rm ${pplfile}
+fi
